server:
  port: 8888
spring:
  application:
    name: druid-example
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 654321

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.prospect.druid.bean.db
  configuration:
    map-underscore-to-camel-case: true

